#!/bin/sh

persist=/var/lib/boot-digest
base=`dirname $0`
mytemp=/tmp/boot.digest.$$
myreturn=1

cleanup() {
	rm -fr "${mytemp}"
}
trap cleanup 0

mkdir -p "${mytemp}"
"${base}/boot-digest-calc" > "${mytemp}/digest"

out=`diff -uNpr "${persist}/digest" "${mytemp}/digest" 2>&1`
if [ $? = 0 ]; then
	myreturn=0
else
	wall <<__EOF__
Bad boot digest!!! (${f})
${out}
__EOF__
fi

exit ${myreturn}
