#!/bin/sh

part=`mount | grep boot | cut -f 1 -d ' '`
disk=`echo "${part}" | sed 's/[0-9]*$//'`
if [ -z "${disk}" ]; then
	echo "Cannot determind boot disk" | wall
else
	for u in md5sum sha512sum; do
		echo "${disk}"
		dd "if=${disk}" bs=512 count=1 status=noxfer 2> /dev/null | ${u}
		echo "${part}"
		dd "if=${part}" status=noxfer 2> /dev/null | ${u}
	done
fi

exit 0
