#!/bin/sh

bootdir=/boot
persist=/var/lib/boot-digest
base=`dirname $0`
mytemp=/tmp/boot.digest.$$
boot_mounted=0
myreturn=1

cleanup() {
	rm -fr "${mytemp}"
}
trap cleanup 0

if mount | grep "${bootdir}" > /dev/null; then
	boot_mounted=1
fi

if [ "${boot_mounted}" = 0 ]; then
	if ! mount -o ro "${bootdir}"; then
		echo "Cannot mount boot parition ${bootdir}" >&2
		echo "Bad boot digest!!! Cannot mount boot parition ${bootdir}" | wall
		exit 1
	fi
fi

mkdir -p "${mytemp}"
"${base}/boot-digest-calc" > "${mytemp}/digest"

out=`diff -uNpr "${persist}/digest" "${mytemp}/digest" 2>&1`
if [ $? == 0 ]; then
	myreturn=0
else
	wall <<__EOF__
Bad boot digest!!! (${f})
${out}
__EOF__
fi

[ "${boot_mounted}" = 0 ] && umount "${bootdir}"

exit ${myreturn}
